name: Build and Release APK

on:
  push:
    tags:
      - 'v*.*.*' # Triggers on tags like v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Decode Keystore
        id: decode_keystore
        env:
          SIGNING_KEY_JKS_BASE64: ${{ secrets.SIGNING_KEY_JKS_BASE64 }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: |
          echo $SIGNING_KEY_JKS_BASE64 | base64 --decode > ${{ github.workspace }}/keystore.jks
          echo "storeFile=${{ github.workspace }}/keystore.jks" > ${{ github.workspace }}/keystore.properties
          echo "storePassword=$SIGNING_STORE_PASSWORD" >> ${{ github.workspace }}/keystore.properties
          echo "keyAlias=$SIGNING_KEY_ALIAS" >> ${{ github.workspace }}/keystore.properties
          echo "keyPassword=$SIGNING_KEY_PASSWORD" >> ${{ github.workspace }}/keystore.properties

      - name: Build Release APK
        run: ./gradlew :app:assembleRelease

      - name: Find APK
        id: find_apk
        run: |
          apk_path=$(find app/build/outputs/apk/release -name "*.apk" | head -n 1)
          echo "apk_path=$apk_path" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.find_apk.outputs.apk_path }}
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
